added manpage, added makefile, added more error checks

diff --git a/usync b/usync
--- a/usync
+++ b/usync
@@ -3,7 +3,7 @@
 
 print_help() { cat <<'HELPDOC'
 NAME
-    usync - push/pull changes from remote source
+    usync - push/pull changes from remote host
 
 SYNOPSIS
     usync <command> [option...]
@@ -11,8 +11,7 @@ SYNOPSIS
 DESCRIPTION
     Usync is an rsync wrapper controlled by a simple config file. Usync
     searches the current and parent directories for a .usync file that defines
-    a remote rsync host. COMMAND is executed in root directory containing
-    .usync file.
+    a remote rsync host and base working directory.
 
 COMMANDS
     init
@@ -26,22 +25,24 @@ COMMANDS
 
 OPTIONS
     -c, --config <file>
-        Use config FILE.
+        Set config file basename. Usync searches current and parent directories
+        for <file> and uses that file and directory as its configuration and
+        base working directory.
 
     -d, --dir <directory>
-        Set remote directory.
+        Set remote rsync directory.
 
     -e, --exclude <pattern>
         Add to exclude patterns.
 
     -p, --port <port>
-        Set port number.
+        Set remote port number.
 
     -r, --remote, --url <url>
-        Set remote url.
+        Set remote rsync url.
 
     -u, --user <user>
-        Set remote user.
+        Set remote rsync/ssh user.
 
     -D, --dryrun
         Perform dry run making no changes.
@@ -50,7 +51,7 @@ OPTIONS
         Don't write anything to stdout.
 
     -V, --verbose
-        Show rsync command.
+        Print more verbose information.
 
     --nocolor
         Disable colored output.
@@ -61,21 +62,21 @@ OPTIONS
 CONFIG
     .usync - yaml file containing the following keys:
 
-        dir
-            Remote repo directory. Must be a full path. (required)
+    dir
+        Remote repo directory. Must be a full path. (required)
 
-        remote or url
-            Remote repo url. May be an ssh alias. (optional)
+    remote or url
+        Remote repo url. May be an ssh alias. (required)
 
-        port
-            Remote port. (optional)
+    port
+        Remote port. (optional)
 
-        user
-            Remote user. (optional)
+    user
+        Remote user. (optional)
 
-        exclude
-            List of patterns to exclude via rsync --exclude option. (optional)
-            See FILTER RULES section of rsync manual for details and syntax.
+    exclude
+        List of patterns to exclude via rsync --exclude option. (optional)
+        See FILTER RULES section of rsync manual for details and syntax.
 
 ENVIRONMENT
     NOCOLOR=1
@@ -94,8 +95,8 @@ HELPDOC
 [[ "$0" != "$BASH_SOURCE" ]] && print_help && return 0
 
 ## settings ::
-readonly deps=(rsync ssh)
-readonly opts=(init pull push -c: --config: -d: --dir: -e: --exclude: -p: --port: -r: --remote: --url: -u: --user: -D --dryrun -Q --quiet -V --verbose --debug --nocolor -H --help)
+readonly -a deps=(rsync ssh)
+readonly -a opts=(init pull push -c: --config: -d: --dir: -e: --exclude: -p: --port: -r: --remote: --url: -u: --user: -D --dryrun -Q --quiet -V --verbose --debug --nocolor -H --help)
 
 # defaults:
 DEBUG="${DEBUG:-0}"
@@ -104,29 +105,18 @@ QUIET="${QUIET:-0}"
 VERBOSE="${VERBOSE:-0}"
 
 ## internal functions/variables ::
-readonly args=("$@")
-args_operands=()
-args_options=()
-args_parsed=()
-conf=.usync
-dir=
-dryrun=0
+readonly -a args=("$@")
+args_operands=() args_options=() args_parsed=()
+init=0 pull=0 push=0 dryrun=0
+declare opt_dir opt_port opt_remote opt_user
+dir= port= remote= user=
 excludes=()
+conf=.usync
 host="$HOSTNAME"
 in_exclude=0
-init=0
-opt_dir=
-opt_port=
-opt_remote=
-opt_user=
-port=
-pull=0
-push=0
 remote_dir=
-remote=localhost
 rsync_args=(-azz --protect-args '--info=copy1,del1,name1' --delete)
 sed_args=()
-user=
 
 # colors:
 blue=$'\e[38;5;12m'
@@ -244,6 +234,11 @@ for d in "${deps[@]}"; do is_cmd "$d" || error "missing dependency: $d"; done
 [[ ${#args_operands[@]} -gt 0 ]] && error_opt "${args_operands[0]}"
 ((init+push+pull-1)) && error 'too many commands'
 ! ((init+push+pull)) && msg_warn 'no command' && exit 0
+[[ "$conf" =~ / ]] && error "config file name is not a basename: $conf"
+[[ -z "$conf" ]] && error 'config file name cannot be blank'
+[[ -n "${opt_dir+x}" && -z "$opt_dir" ]] && error 'remote directory name cannot be blank'
+[[ -n "${opt_remote+x}" && -z "$opt_remote" ]] && error 'remote url cannot be blank'
+[[ -z "$opt_port" || ("$opt_port" =~ ^[1-9][0-9]*$ && $opt_port -lt 65536) ]] || error "invalid port: $opt_port"
 
 if ((init)); then
     # create new .usync file in current directory:
@@ -251,7 +246,7 @@ if ((init)); then
     touch "$conf"
     { printf '## %s ::\n\n' "$(realpath "$conf")"
     printf 'dir: %s\n' "${opt_dir:-$PWD}"
-    printf 'url: %s\n' "${opt_remote:-$remote}"
+    printf 'url: %s\n' "${opt_remote:-localhost}"
     [[ -n "$opt_port" ]] && printf 'port: %s\n' "$opt_port"
     [[ -n "$opt_user" ]] && printf 'user: %s\n' "$opt_user"
     printf 'exclude:\n- .git\n- /local\n'
@@ -262,7 +257,7 @@ fi
 
 # cd to nearest parent directory that contains config file:
 while [[ ! -f "$conf" && "$PWD" != '/' ]]; do cd ..; done
-[[ ! -f "$conf" ]] && error "$conf not found"
+[[ ! -f "$conf" ]] && error "config not found: $conf"
 
 # parse config:
 mapfile -t lines < <(sed -E -e 's/(^\s+|\s+$)//g' -e '/^(#|$|-$)/d' "$conf")
@@ -286,12 +281,12 @@ user="${opt_user:-$user}"
 
 # replace leading ~ with $HOME and remove trailing / from dir:
 [[ "${dir:0:1}" = '~' ]] && dir="$HOME${dir:1}"
-[[ "${dir: -1}" = '/' ]] && dir="${dir:0:-1}"
+[[ "${dir: -1}" = '/' && "${#dir}" -gt 1 ]] && dir="${dir:0:-1}"
 
 # config errors:
 [[ -z "$remote" ]] && error 'no remote'
 [[ -z "$dir" ]] && error 'no directory'
-[[ -n "$port" && (! "$port" =~ ^[1-9][0-9]*$ || $port -gt 65535) ]] && error "invalid port: $port"
+[[ -n "$port" && ( ! "$port" =~ ^[1-9][0-9]*$ || $port -gt 65535) ]] && error "invalid port: $port"
 
 # resolve host and remote:
 [[ -f /etc/hostname ]] && host="$(cat /etc/hostname)"
